//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.02 at 08:16:29 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://mindtree.com/studentssoap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.mindtree_com.studentssoap;
